### ISSUE TITLE
Windows Azure Instructions

### ISSUE THREAD

**Issue by lnmunhoz** [sputlytics/sputlytics#13]
https://github.com/christopheranderson/azure-demeteorizer

**Comment by lnmunhoz** [comment]
Azure Deploy Button -> https://github.com/rauchg/slackin

**Comment by caio-ribeiro-pereira** [comment]
@lnmunhoz this slackin link has azure and cloudmix one click deploy button, please, we need to add theses buttons in our landing page.

**Comment by caio-ribeiro-pereira** [comment]
I added the Azure one-click deploy!
